spring.application.name=api-gateway
server.port=9000
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/spring-microsservice
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.urls[0].name=Produto Service
springdoc.swagger-ui.urls[0].url=/aggregate/product-service/v3/api-docs
springdoc.swagger-ui.urls[1].name=Pedido Service
springdoc.swagger-ui.urls[1].url=/aggregate/pedido-service/v3/api-docs
springdoc.swagger-ui.urls[2].name=Inventario Service
springdoc.swagger-ui.urls[2].url=/aggregate/inventario-service/v3/api-docs

logging.level.org.springframework.security=DEBUG