/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.projeto.pedido_service.event;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PedidoFeitoEvent extends org.apache.avro.specific.SpecificRecordBase {
  private static final long serialVersionUID = 3857029275470194859L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PedidoFeitoEvent\",\"namespace\":\"com.projeto.pedido_service.event\",\"fields\":[{\"name\":\"numeroPedido\",\"type\":\"string\"},{\"name\":\"email\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PedidoFeitoEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PedidoFeitoEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PedidoFeitoEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PedidoFeitoEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PedidoFeitoEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PedidoFeitoEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PedidoFeitoEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PedidoFeitoEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PedidoFeitoEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence numeroPedido;
  private java.lang.CharSequence email;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PedidoFeitoEvent() {}

  /**
   * All-args constructor.
   * @param numeroPedido The new value for numeroPedido
   * @param email The new value for email
   */
  public PedidoFeitoEvent(java.lang.CharSequence numeroPedido, java.lang.CharSequence email) {
    this.numeroPedido = numeroPedido;
    this.email = email;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return numeroPedido;
    case 1: return email;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: numeroPedido = (java.lang.CharSequence)value$; break;
    case 1: email = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'numeroPedido' field.
   * @return The value of the 'numeroPedido' field.
   */
  public java.lang.CharSequence getNumeroPedido() {
    return numeroPedido;
  }


  /**
   * Sets the value of the 'numeroPedido' field.
   * @param value the value to set.
   */
  public void setNumeroPedido(java.lang.CharSequence value) {
    this.numeroPedido = value;
  }

  /**
   * Gets the value of the 'email' field.
   * @return The value of the 'email' field.
   */
  public java.lang.CharSequence getEmail() {
    return email;
  }


  /**
   * Sets the value of the 'email' field.
   * @param value the value to set.
   */
  public void setEmail(java.lang.CharSequence value) {
    this.email = value;
  }

  /**
   * Creates a new PedidoFeitoEvent RecordBuilder.
   * @return A new PedidoFeitoEvent RecordBuilder
   */
  public static com.projeto.pedido_service.event.PedidoFeitoEvent.Builder newBuilder() {
    return new com.projeto.pedido_service.event.PedidoFeitoEvent.Builder();
  }

  /**
   * Creates a new PedidoFeitoEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PedidoFeitoEvent RecordBuilder
   */
  public static com.projeto.pedido_service.event.PedidoFeitoEvent.Builder newBuilder(com.projeto.pedido_service.event.PedidoFeitoEvent.Builder other) {
    if (other == null) {
      return new com.projeto.pedido_service.event.PedidoFeitoEvent.Builder();
    } else {
      return new com.projeto.pedido_service.event.PedidoFeitoEvent.Builder(other);
    }
  }

  /**
   * Creates a new PedidoFeitoEvent RecordBuilder by copying an existing PedidoFeitoEvent instance.
   * @param other The existing instance to copy.
   * @return A new PedidoFeitoEvent RecordBuilder
   */
  public static com.projeto.pedido_service.event.PedidoFeitoEvent.Builder newBuilder(com.projeto.pedido_service.event.PedidoFeitoEvent other) {
    if (other == null) {
      return new com.projeto.pedido_service.event.PedidoFeitoEvent.Builder();
    } else {
      return new com.projeto.pedido_service.event.PedidoFeitoEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for PedidoFeitoEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PedidoFeitoEvent>{

    private java.lang.CharSequence numeroPedido;
    private java.lang.CharSequence email;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.projeto.pedido_service.event.PedidoFeitoEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.numeroPedido)) {
        this.numeroPedido = data().deepCopy(fields()[0].schema(), other.numeroPedido);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.email)) {
        this.email = data().deepCopy(fields()[1].schema(), other.email);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing PedidoFeitoEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.projeto.pedido_service.event.PedidoFeitoEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.numeroPedido)) {
        this.numeroPedido = data().deepCopy(fields()[0].schema(), other.numeroPedido);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.email)) {
        this.email = data().deepCopy(fields()[1].schema(), other.email);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'numeroPedido' field.
      * @return The value.
      */
    public java.lang.CharSequence getNumeroPedido() {
      return numeroPedido;
    }


    /**
      * Sets the value of the 'numeroPedido' field.
      * @param value The value of 'numeroPedido'.
      * @return This builder.
      */
    public com.projeto.pedido_service.event.PedidoFeitoEvent.Builder setNumeroPedido(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.numeroPedido = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'numeroPedido' field has been set.
      * @return True if the 'numeroPedido' field has been set, false otherwise.
      */
    public boolean hasNumeroPedido() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'numeroPedido' field.
      * @return This builder.
      */
    public com.projeto.pedido_service.event.PedidoFeitoEvent.Builder clearNumeroPedido() {
      numeroPedido = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'email' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmail() {
      return email;
    }


    /**
      * Sets the value of the 'email' field.
      * @param value The value of 'email'.
      * @return This builder.
      */
    public com.projeto.pedido_service.event.PedidoFeitoEvent.Builder setEmail(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.email = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'email' field has been set.
      * @return True if the 'email' field has been set, false otherwise.
      */
    public boolean hasEmail() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'email' field.
      * @return This builder.
      */
    public com.projeto.pedido_service.event.PedidoFeitoEvent.Builder clearEmail() {
      email = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public PedidoFeitoEvent build() {
      try {
        PedidoFeitoEvent record = new PedidoFeitoEvent();
        record.numeroPedido = fieldSetFlags()[0] ? this.numeroPedido : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.email = fieldSetFlags()[1] ? this.email : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PedidoFeitoEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<PedidoFeitoEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PedidoFeitoEvent>
    READER$ = (org.apache.avro.io.DatumReader<PedidoFeitoEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.numeroPedido);

    out.writeString(this.email);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.numeroPedido = in.readString(this.numeroPedido instanceof Utf8 ? (Utf8)this.numeroPedido : null);

      this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.numeroPedido = in.readString(this.numeroPedido instanceof Utf8 ? (Utf8)this.numeroPedido : null);
          break;

        case 1:
          this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










